
# # Notebook 03 - Data Cleaning & Transformation
# Objective: Create clean listing datasets for London and New York.

In [1]:
import pandas as pd
import numpy as np

In [2]:
london_listings = pd.read_csv("../data/raw/london/listings.csv.gz")
ny_listings = pd.read_csv("../data/raw/new_york/listings.csv.gz")

london_clean = london_listings.copy()
ny_clean = ny_listings.copy()

In [3]:
def clean_price_column(df, source_col="price", target_col="price_clean"):
    df[target_col] = (
        df[source_col]
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .astype(float)
    )
    return df

In [4]:
london_clean = clean_price_column(london_clean)
ny_clean = clean_price_column(ny_clean)

print(london_clean[["price", "price_clean"]].head())
print(ny_clean[["price", "price_clean"]].head())

     price  price_clean
0   $70.00         70.0
1  $149.00        149.0
2  $411.00        411.0
3      NaN          NaN
4  $210.00        210.0
     price  price_clean
0  $117.27       117.27
1   $66.87        66.87
2   $77.17        77.17
3  $202.47       202.47
4  $365.97       365.97

In [5]:
london_clean["price_outlier"] = london_clean["price_clean"] > 1100
ny_clean["price_outlier"] = ny_clean["price_clean"] > 1562

print("London price outliers:", london_clean["price_outlier"].sum())
print("NY price outliers:", ny_clean["price_outlier"].sum())

London price outliers: 613
NY price outliers: 207

In [6]:
print("London Columns:", len(london_clean.columns))
print("NY Columns:", len(ny_clean.columns))

London Columns: 81
NY Columns: 92

In [7]:
london_clean[
    [
        "license",
        "calendar_updated",
        "neighbourhood_group_cleansed"
    ]
].head()

   license  calendar_updated  neighbourhood_group_cleansed
0      NaN               NaN                           NaN
1      NaN               NaN                           NaN
2      NaN               NaN                           NaN
3      NaN               NaN                           NaN
4      NaN               NaN                           NaN

In [8]:
ny_clean[
    [
        "calendar_updated"
    ]
].head()

   calendar_updated
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN


# ## Column Removal
#
# Objective:
# Remove columns containing no usable information
# to reduce dataset complexity and improve quality.

In [9]:
london_clean = london_clean.drop(
    columns=[
        "license",
        "calendar_updated",
        "neighbourhood_group_cleansed"
    ]
)

ny_clean = ny_clean.drop(
    columns=[
        "calendar_updated"
    ]
)

In [10]:
print("London Columns:", len(london_clean.columns))
print("NY Columns:", len(ny_clean.columns))

London Columns: 78
NY Columns: 91

In [11]:
london_missing_after = (
    london_clean.isnull()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

ny_missing_after = (
    ny_clean.isnull()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print("London")
print(london_missing_after.head(15))

print("\nNY")
print(ny_missing_after.head(15))

London
neighborhood_overview      57.460953
neighbourhood              57.459921
host_neighbourhood         52.669013
host_about                 48.557360
beds                       36.047940
price                      36.035552
estimated_revenue_l365d    36.035552
price_clean                36.035552
bathrooms                  35.971550
host_response_time         32.731158
host_response_rate         32.731158
host_acceptance_rate       28.656667
review_scores_location     24.946578
review_scores_value        24.946578
review_scores_checkin      24.945546
dtype: float64

NY
neighborhood_overview        100.000000
host_thumbnail_url           100.000000
host_since                   100.000000
host_response_rate           100.000000
host_response_time           100.000000
host_acceptance_rate         100.000000
instant_bookable             100.000000
neighbourhood                100.000000
host_verifications           100.000000
host_total_listings_count    100.000000
host_neighbourhood           100.000000
beds                          89.265327
bathrooms                     89.162576
license                       85.552004
host_about                    43.923393
dtype: float64

In [12]:
print("London rows:", len(london_clean))
print(
    "London rows missing price:",
    london_clean["price_clean"].isnull().sum()
)

print("NY rows:", len(ny_clean))
print(
    "NY rows missing price:",
    ny_clean["price_clean"].isnull().sum()
)

London rows: 96871
London rows missing price: 34908
NY rows: 35036
NY rows missing price: 14343

In [16]:
review_cols = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month"
]

london_clean[review_cols].isnull().mean().mul(100)

review_scores_rating           24.901157
review_scores_accuracy         24.916642
review_scores_cleanliness      24.910448
review_scores_checkin          24.945546
review_scores_communication    24.921803
review_scores_location         24.946578
review_scores_value            24.946578
reviews_per_month              24.901157
dtype: float64

In [15]:
review_cols = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month"
]
ny_clean[review_cols].isnull().mean().mul(100)

review_scores_rating           29.952049
review_scores_accuracy         29.980591
review_scores_cleanliness      29.954904
review_scores_checkin          29.992008
review_scores_communication    29.969175
review_scores_location         30.000571
review_scores_value            29.997717
reviews_per_month              29.952049
dtype: float64

In [17]:
london_clean[["number_of_reviews","review_scores_rating","reviews_per_month"]].head(20)

    number_of_reviews  review_scores_rating  reviews_per_month
0                  55                  4.85               0.30
1                  97                  4.80               0.51
2                  56                  4.77               0.32
3                  95                  4.90               0.53
4                  15                  4.53               0.09
5                 116                  4.80               0.64
6                 730                  4.87               4.00
7                 387                  4.77               2.14
8                  42                  4.83               0.26
9                  72                  4.97               1.06
10                 10                  4.50               0.07
11                 25                  4.50               0.15
12                 71                  4.50               0.41
13                137                  4.70               0.77
14                  2                  4.50               0.01
15                639                  4.89               3.50
16                  0                   NaN                NaN
17                266                  4.74               1.79
18                145                  4.88               0.91
19                  1                  5.00               0.02

In [18]:
ny_clean[["number_of_reviews","review_scores_rating","reviews_per_month"]].head(20)

    number_of_reviews  review_scores_rating  reviews_per_month
0                 197                  4.60               0.96
1                   2                  5.00               0.04
2                 251                  4.88               1.25
3                 423                  4.89               2.14
4                  13                  4.92               0.06
5                 189                  4.77               0.93
6                  58                  4.52               0.29
7                  82                  4.66               0.42
8                   0                   NaN                NaN
9                 316                  4.40               1.58
10                 81                  4.59               0.41
11                177                  4.83               0.89
12                 63                  4.87               0.33
13                  5                  5.00               0.04
14                 33                  4.67               0.17
15                173                  4.82               0.94
16                266                  4.59               1.43
17                  0                   NaN                NaN
18                258                  4.79               1.41
19                 56                  4.67               0.30

In [19]:
print("London Beds Missing:",
      london_clean["beds"].isnull().sum())

print("London Bathrooms Missing:",
      london_clean["bathrooms"].isnull().sum())

print("\nNY Beds Missing:",
      ny_clean["beds"].isnull().sum())

print("NY Bathrooms Missing:",
      ny_clean["bathrooms"].isnull().sum())

London Beds Missing: 34920
London Bathrooms Missing: 34846

NY Beds Missing: 31275
NY Bathrooms Missing: 31239

In [20]:
london_clean[
    [
        "property_type",
        "room_type",
        "beds",
        "bathrooms"
    ]
].sample(10, random_state=42)

                           property_type        room_type  beds  bathrooms
56789                       Entire place  Entire home/apt   1.0        1.0
4670                         Entire home  Entire home/apt   NaN        NaN
29262                       Entire condo  Entire home/apt   2.0        2.5
39409          Private room in townhouse     Private room   NaN        NaN
48769        Private room in rental unit     Private room   1.0        1.0
59695                 Entire rental unit  Entire home/apt   2.0        2.0
38869               Private room in home     Private room   NaN        NaN
2182                  Entire rental unit  Entire home/apt   2.0        1.0
83017                 Entire rental unit  Entire home/apt   2.0        2.0
35759  Private room in bed and breakfast     Private room   NaN        NaN

In [21]:
ny_clean[
    [
        "property_type",
        "room_type",
        "beds",
        "bathrooms"
    ]
].sample(10, random_state=42)

                     property_type        room_type  beds  bathrooms
30413  Private room in rental unit     Private room   NaN        NaN
896    Private room in rental unit     Private room   NaN        NaN
29364  Private room in rental unit     Private room   NaN        NaN
32696           Entire rental unit  Entire home/apt   NaN        NaN
32776           Entire rental unit  Entire home/apt   NaN        NaN
28105           Entire rental unit  Entire home/apt   NaN        NaN
29698         Private room in home     Private room   NaN        NaN
18515    Private room in townhouse     Private room   NaN        NaN
29211                Room in hotel     Private room   NaN        NaN
928             Entire rental unit  Entire home/apt   NaN        NaN

In [22]:
date_cols = [
    col for col in london_clean.columns
    if "date" in col.lower()
]

print(date_cols)

['accommodates']

In [23]:
date_cols_ny = [
    col for col in ny_clean.columns
    if "date" in col.lower()
]

print(date_cols_ny)

['accommodates', 'price_quote_checkin_date', 'price_quote_checkout_date']

In [24]:
possible_date_cols_london = [
    col for col in london_clean.columns
    if (
        col.endswith("_date")
        or col.endswith("_scraped")
        or col in ["host_since", "first_review", "last_review"]
    )
]

possible_date_cols_ny = [
    col for col in ny_clean.columns
    if (
        col.endswith("_date")
        or col.endswith("_scraped")
        or col in ["host_since", "first_review", "last_review"]
    )
]

print("London:", possible_date_cols_london)
print("NY:", possible_date_cols_ny)

London: ['last_scraped', 'host_since', 'calendar_last_scraped', 'first_review', 'last_review']
NY: ['last_scraped', 'host_since', 'price_quote_checkin_date', 'price_quote_checkout_date', 'calendar_last_scraped', 'first_review', 'last_review']

In [25]:
for col in possible_date_cols_london:
    london_clean[col] = pd.to_datetime(london_clean[col], errors="coerce")

for col in possible_date_cols_ny:
    ny_clean[col] = pd.to_datetime(ny_clean[col], errors="coerce")

In [26]:
print("London date dtypes:")
print(london_clean[possible_date_cols_london].dtypes)

print("\nNY date dtypes:")
print(ny_clean[possible_date_cols_ny].dtypes)

London date dtypes:
last_scraped             datetime64[us]
host_since               datetime64[us]
calendar_last_scraped    datetime64[us]
first_review             datetime64[us]
last_review              datetime64[us]
dtype: object

NY date dtypes:
last_scraped                 datetime64[us]
host_since                    datetime64[s]
price_quote_checkin_date     datetime64[us]
price_quote_checkout_date    datetime64[us]
calendar_last_scraped        datetime64[us]
first_review                 datetime64[us]
last_review                  datetime64[us]
dtype: object

In [27]:
london_clean["host_tenure_years"] = (
    (london_clean["last_scraped"] - london_clean["host_since"]).dt.days / 365
)

ny_clean["host_tenure_years"] = (
    (ny_clean["last_scraped"] - ny_clean["host_since"]).dt.days / 365
)

In [28]:
print("London host tenure:")
print(london_clean["host_tenure_years"].describe())

print("\nNY host tenure:")
print(ny_clean["host_tenure_years"].describe())

London host tenure:
count    96830.000000
mean         7.650425
std          3.896901
min          0.008219
25%          4.063014
50%          8.580822
75%         10.591781
max         17.060274
Name: host_tenure_years, dtype: float64

NY host tenure:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: host_tenure_years, dtype: float64

In [29]:
print("London shape:", london_clean.shape)
print("NY shape:", ny_clean.shape)

print("\nLondon memory (MB):")
print(
    london_clean.memory_usage(deep=True).sum() / 1024**2
)

print("\nNY memory (MB):")
print(
    ny_clean.memory_usage(deep=True).sum() / 1024**2
)

London shape: (96871, 79)
NY shape: (35036, 92)

London memory (MB):
222.89298915863037

NY memory (MB):
88.42061996459961

In [30]:
london_clean.to_csv("../data/processed/london_listings_clean.csv", index=False)
ny_clean.to_csv("../data/processed/ny_listings_clean.csv", index=False)